apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: wechat-applet-back
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wechat-applet-back
    spec:
      containers:
      - name: wechat-applet-back
        image: redis
        ports:
        - containerPort: 6379
          name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: wechat-applet-back
spec:
  ports:
  - port: 6379
  selector:
    app: wechat-applet-back
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: wechat-applet-front
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: wechat-applet-front
    spec:
      containers:
      - name: wechat-applet-front
        image: foamliu.azurecr.io/wechat-applet-front:v1
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: REDIS
          value: "wechat-applet-back"
---
apiVersion: v1
kind: Service
metadata:
  name: wechat-applet-front
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: wechat-applet-front